###### ОБЩИЕ ДЛЯ ВСЕХ ######
REGION = [
    ('Брестская', 'Брестская'),
    ('Гомельская', 'Гомельская'),
    ('Гродненская', 'Гродненская'),
    ('Могилевская', 'Могилевская'),
    ('Минская', 'Минская'),
    ('Витебская', 'Витебская'),
]   # область
CITY = [
    ('Брест', 'Брест'),
    ('Барановичи', 'Барановичи'),
    ('Береза', 'Береза'),
    ('Белоозёрск', 'Белоозёрск'),
    ('Высокое', 'Высокое'),
    ('Ганцевичи', 'Ганцевичи'),
    ('Давид', 'Давид'),
    ('Дрогичин', 'Дрогичин'),
    ('Жабинка', 'Жабинка'),
    ('Иваново', 'Иваново'),
    ('Ивацевичи', 'Ивацевичи'),
    ('Каменец', 'Каменец'),
    ('Кобрин', 'Кобрин'),
    ('Лунинец', 'Лунинец'),
    ('Ляховичи', 'Ляховичи'),
    ('Малорита', 'Малорита'),
    ('Микашевичи', 'Микашевичи'),
    ('Пинск', 'Пинск'),
    ('Пружаны', 'Пружаны'),
    ('Столин', 'Столин'),
    ('Гомель', 'Гомель'),
    ('Брагин', 'Брагин'),
    ('Буда', 'Буда'),
    ('Василевичи', 'Василевичи'),
    ('Ветка', 'Ветка'),
    ('Добруш', 'Добруш'),
    ('Ельск', 'Ельск'),
    ('Житковичи', 'Житковичи'),
    ('Жлобин', 'Жлобин'),
    ('Калинковичи', 'Калинковичи'),
    ('Корма', 'Корма'),
    ('Лельчицы', 'Лельчицы'),
    ('Лоев', 'Лоев'),
    ('Мозырь', 'Мозырь'),
    ('г.п. Октябрьский', 'г.п. Октябрьский'),
    ('Наровля', 'Наровля'),
    ('Петриков', 'Петриков'),
    ('Речица', 'Речица'),
    ('Рогачев', 'Рогачев'),
    ('Светлогорск', 'Светлогорск'),
    ('Хойники', 'Хойники'),
    ('Чечерск', 'Чечерск'),
    ('Гродно', 'Гродно'),
    ('Березовка', 'Березовка'),
    ('Берестовица', 'Берестовица'),
    ('Волковыск', 'Волковыск'),
    ('Вороново', 'Вороново'),
    ('Дятлово', 'Дятлово'),
    ('Зельва', 'Зельва'),
    ('Ивье', 'Ивье'),
    ('Кореличи', 'Кореличи'),
    ('Лида', 'Лида'),
    ('Мосты', 'Мосты'),
    ('Новогрудок', 'Новогрудок'),
    ('Островец', 'Островец'),
    ('Ошмяны', 'Ошмяны'),
    ('Свислочь', 'Свислочь'),
    ('Скидель', 'Скидель'),
    ('Слоним', 'Слоним'),
    ('Сморгонь', 'Сморгонь'),
    ('Щучин', 'Щучин'),
    ('Могилев', 'Могилев'),
    ('Белыничи', 'Белыничи'),
    ('Бобруйск', 'Бобруйск'),
    ('Быхов', 'Быхов'),
    ('Глуск', 'Глуск'),
    ('Горки', 'Горки'),
    ('Дрибин', 'Дрибин'),
    ('Кировск', 'Кировск'),
    ('Климовичи', 'Климовичи'),
    ('Кличев', 'Кличев'),
    ('Краснополье', 'Краснополье'),
    ('Круглое', 'Круглое'),
    ('Костюковичи', 'Костюковичи'),
    ('Кричев', 'Кричев'),
    ('Мстиславль', 'Мстиславль'),
    ('Осиповичи', 'Осиповичи'),
    ('Славгород', 'Славгород'),
    ('Чаусы', 'Чаусы'),
    ('Чериков', 'Чериков'),
    ('Шклов', 'Шклов'),
    ('Хотимск', 'Хотимск'),
    ('Минск', 'Минск'),
    ('Березино', 'Березино'),
    ('Борисов', 'Борисов'),
    ('Вилейка', 'Вилейка'),
    ('Воложин', 'Воложин'),
    ('Дзержинск', 'Дзержинск'),
    ('Жодино', 'Жодино'),
    ('Заславль', 'Заславль'),
    ('Клецк', 'Клецк'),
    ('Копыль', 'Копыль'),
    ('Крупки', 'Крупки'),
    ('Логойск', 'Логойск'),
    ('Любань', 'Любань'),
    ('Марьина горка', 'Марьина горка'),
    ('Молодечно', 'Молодечно'),
    ('Мядель', 'Мядель'),
    ('Несвиж', 'Несвиж'),
    ('Руденск', 'Руденск'),
    ('Слуцк', 'Слуцк'),
    ('Смолевичи', 'Смолевичи'),
    ('Солигорск', 'Солигорск'),
    ('Старые', 'Старые'),
    ('Столбцы', 'Столбцы'),
    ('Узда', 'Узда'),
    ('Фаниполь', 'Фаниполь'),
    ('Червень', 'Червень'),
    ('Витебск', 'Витебск'),
    ('Бешенковичи', 'Бешенковичи'),
    ('Барань', 'Барань'),
    ('Браслав', 'Браслав'),
    ('Верхнедвинск', 'Верхнедвинск'),
    ('Глубокое', 'Глубокое'),
    ('Городок', 'Городок'),
    ('Докшицы', 'Докшицы'),
    ('Дубровно', 'Дубровно'),
    ('Лепель', 'Лепель'),
    ('Лиозно', 'Лиозно'),
    ('Миоры', 'Миоры'),
    ('Новолукомль', 'Новолукомль'),
    ('Новополоцк', 'Новополоцк'),
    ('Орша', 'Орша'),
    ('Полоцк', 'Полоцк'),
    ('Поставы', 'Поставы'),
    ('Россоны', 'Россоны'),
    ('Сенно', 'Сенно'),
    ('Толочин', 'Толочин'),
    ('Ушачи', 'Ушачи'),
    ('Чашники', 'Чашники'),
    ('Шарковщина', 'Шарковщина'),
    ('Шумилино', 'Шумилино'),
]   # город

###### ЛЕГКОВЫЕ АВТО ######
CAR_BRAND = [
    ("Abarth", "Abarth"),
    ("Dongfeng", "Dongfeng"),
    ("Jaguar", "Jaguar"),
    ("Nissan", "Nissan"),
    ("Tata", "Tata"),
    ("Acura", "Acura"),
    ("Dongfeng Honda", "Dongfeng Honda"),
    ("Jeep", "Jeep"),
    ("Oldsmobile", "Oldsmobile"),
    ("Tatra", "Tatra"),
    ("Aeolus", "Aeolus"),
    ("Eagle", "Eagle"),
    ("Jetour", "Jetour"),
    ("Omoda", "Omoda"),
    ("Tesla", "Tesla"),
    ("Aito", "Aito"),
    ("Everus", "Everus"),
    ("Jetta", "Jetta"),
    ("Opel", "Opel"),
    ("Think", "Think"),
    ("Alfa Romeo", "Alfa Romeo"),
    ("EXEED", "EXEED"),
    ("Jiangling", "Jiangling"),
    ("Peugeot", "Peugeot"),
    ("Tianma", "Tianma"),
    ("Alpina", "Alpina"),
    ("FAW", "FAW"),
    ("Jinbei", "Jinbei"),
    ("Piaggio", "Piaggio"),
    ("Toyota", "Toyota"),
    ("ARO", "ARO"),
    ("Ferrari", "Ferrari"),
    ("Joylong", "Joylong"),
    ("Plymouth", "Plymouth"),
    ("Trabant", "Trabant"),
    ("Asia", "Asia"),
    ("Fiat", "Fiat"),
    ("Kaiyi", "Kaiyi"),
    ("Polestar", "Polestar"),
    ("VGV", "VGV"),
    ("Aston Martin", "Aston Martin"),
    ("Fisker", "Fisker"),
    ("Kandi", "Kandi"),
    ("Pontiac", "Pontiac"),
    ("Volkswagen", "Volkswagen"),
    ("Audi", "Audi"),
    ("Ford", "Ford"),
    ("Kia", "Kia"),
    ("Porsche", "Porsche"),
    ("Volvo", "Volvo"),
    ("Avatr", "Avatr"),
    ("Foton", "Foton"),
    ("Lada (ВАЗ)", "Lada (ВАЗ)"),
    ("Proton", "Proton"),
    ("Vortex", "Vortex"),
    ("BAIC", "BAIC"),
    ("FSO", "FSO"),
    ("Lamborghini", "Lamborghini"),
    ("RAM", "RAM"),
    ("Voyah", "Voyah"),
    ("Baojun", "Baojun"),
    ("GAC", "GAC"),
    ("Lancia", "Lancia"),
    ("Ravon", "Ravon"),
    ("Wartburg", "Wartburg"),
    ("Belgee", "Belgee"),
    ("GAC Honda", "GAC Honda"),
    ("Land Rover", "Land Rover"),
    ("Renault", "Renault"),
    ("Weltmeister", "Weltmeister"),
    ("Bentley", "Bentley"),
    ("Geely", "Geely"),
    ("Leapmotor", "Leapmotor"),
    ("Renault Samsung", "Renault Samsung"),
    ("Wuling", "Wuling"),
    ("BMW", "BMW"),
    ("Genesis", "Genesis"),
    ("Lexus", "Lexus"),
    ("Roewe", "Roewe"),
    ("Xpeng", "Xpeng"),
    ("Brilliance", "Brilliance"),
    ("GMC", "GMC"),
    ("Lifan", "Lifan"),
    ("Rolls-Royce", "Rolls-Royce"),
    ("Yudo", "Yudo"),
    ("Buick", "Buick"),
    ("Gonow", "Gonow"),
    ("Lincoln", "Lincoln"),
    ("Rover", "Rover"),
    ("Zeekr", "Zeekr"),
    ("BYD", "BYD"),
    ("Great Wall", "Great Wall"),
    ("LiXiang", "LiXiang"),
    ("Saab", "Saab"),
    ("Zotye", "Zotye"),
    ("Cadillac", "Cadillac"),
    ("Hafei", "Hafei"),
    ("Lotus", "Lotus"),
    ("Saipa", "Saipa"),
    ("ZX", "ZX"),
    ("Chana", "Chana"),
    ("Haima", "Haima"),
    ("Lynk & Co", "Lynk & Co"),
    ("Santana", "Santana"),
    ("Богдан", "Богдан"),
    ("Changan", "Changan"),
    ("Haval", "Haval"),
    ("Mahindra", "Mahindra"),
    ("Saturn", "Saturn"),
    ("ГАЗ", "ГАЗ"),
    ("Chery", "Chery"),
    ("HiPhi", "HiPhi"),
    ("Maserati", "Maserati"),
    ("Scion", "Scion"),
    ("ЕрАЗ", "ЕрАЗ"),
    ("Chevrolet", "Chevrolet"),
    ("Honda", "Honda"),
    ("Maybach", "Maybach"),
    ("SEAT", "SEAT"),
    ("ЗАЗ", "ЗАЗ"),
    ("Chrysler", "Chrysler"),
    ("Hongqi", "Hongqi"),
    ("Mazda", "Mazda"),
    ("Seres", "Seres"),
    ("ИЖ", "ИЖ"),
    ("Citroen", "Citroen"),
    ("Hongxing", "Hongxing"),
    ("McLaren", "McLaren"),
    ("Shanghai Maple", "Shanghai Maple"),
    ("ЛуАЗ", "ЛуАЗ"),
    ("Cupra", "Cupra"),
    ("Hozon", "Hozon"),
    ("Mercedes-Benz", "Mercedes-Benz"),
    ("Shineray", "Shineray"),
    ("Москвич", "Москвич"),
    ("Dacia", "Dacia"),
    ("Hummer", "Hummer"),
    ("Mercury", "Mercury"),
    ("Skoda", "Skoda"),
    ("РАФ", "РАФ"),
    ("Daewoo", "Daewoo"),
    ("Hycan", "Hycan"),
    ("MG", "MG"),
    ("Skywell", "Skywell"),
    ("ТагАЗ", "ТагАЗ"),
    ("Daihatsu", "Daihatsu"),
    ("Hyundai", "Hyundai"),
    ("Microcar", "Microcar"),
    ("Smart", "Smart"),
    ("УАЗ", "УАЗ"),
    ("Datsun", "Datsun"),
    ("Infiniti", "Infiniti"),
    ("MINI", "MINI"),
    ("SRM", "SRM"),
    ("Эксклюзив", "Эксклюзив"),
    ("Denza", "Denza"),
    ("Iran Khodro", "Iran Khodro"),
    ("Mitsubishi", "Mitsubishi"),
    ("SsangYong", "SsangYong"),
    ("Derways", "Derways"),
    ("Isuzu", "Isuzu"),
    ("Morgan", "Morgan"),
    ("Subaru", "Subaru"),
    ("Dodge", "Dodge"),
    ("JAC", "JAC"),
    ("Nio", "Nio"),
    ("Suzuki", "Suzuki"),
]   # марки авто
CAR_MODEl = [
    # Abarth
    ("124 Spider", "124 Spider"),
    ("500", "500"),
    ("500c", "500c"),
    ("Punto", "Punto"),

    # Acura
    ("CL", "CL"),
    ("Integra", "Integra"),
    ("RDX", "RDX"),
    ("SLX", "SLX"),
    ("Vigor", "Vigor"),
    ("CSX", "CSX"),
    ("Legend", "Legend"),
    ("RL", "RL"),
    ("TL", "TL"),
    ("ZDX", "ZDX"),
    ("EL", "EL"),
    ("MDX", "MDX"),
    ("RLX", "RLX"),
    ("TLX", "TLX"),
    ("ILX", "ILX"),
    ("NSX", "NSX"),
    ("RSX", "RSX"),
    ("TSX", "TSX"),

    # Aeolus
    ("Huge", "Huge"),
    ("Shine", "Shine"),
    ("Shine GS", "Shine GS"),
    ("Shine Max", "Shine Max"),

    # Aito
    ("M5", "M5"),
    ("M7", "M7"),

    # Alfa Romeo
    ("145", "145"),
    ("159", "159"),
    ("75", "75"),
    ("Giulietta", "Giulietta"),
    ("Sprint", "Sprint"),
    ("146", "146"),
    ("164", "164"),
    ("90", "90"),
    ("GT", "GT"),
    ("Stelvio", "Stelvio"),
    ("147", "147"),
    ("166", "166"),
    ("Alfetta", "Alfetta"),
    ("GTV", "GTV"),
    ("155", "155"),
    ("33", "33"),
    ("Brera", "Brera"),
    ("MiTo", "MiTo"),
    ("156", "156"),
    ("4C", "4C"),
    ("Giulia", "Giulia"),
    ("Spider", "Spider"),

    # Alpina
    ("B3", "B3"),
    ("B5", "B5"),
    ("B7", "B7"),
    ("D5", "D5"),

    # ARO
    ("10", "10"),
    ("24", "24"),
    ("320", "320"),

    # Asia
    ("Rocsta", "Rocsta"),

    # Aston Martin
    ("Cygnet", "Cygnet"),
    ("DB9", "DB9"),
    ("Rapide", "Rapide"),
    ("V8 Vantage", "V8 Vantage"),
    ("DB7", "DB7"),
    ("DBS", "DBS"),
    ("V12 Vantage", "V12 Vantage"),
    ("Virage", "Virage"),

    # Audi
    ("100", "100"),
    ("200", "200"),
    ("50", "50"),
    ("80", "80"),
    ("90", "90"),
    ("920", "920"),
    ("A1", "A1"),
    ("A2", "A2"),
    ("A3", "A3"),
    ("A4", "A4"),
    ("A4 Allroad", "A4 Allroad"),
    ("A5", "A5"),
    ("A6", "A6"),
    ("A6 Allroad", "A6 Allroad"),
    ("A7", "A7"),
    ("A8", "A8"),
    ("Cabriolet", "Cabriolet"),
    ("Coupe", "Coupe"),
    ("E-Tron", "E-Tron"),
    ("E-Tron S", "E-Tron S"),
    ("E-Tron S Sportback", "E-Tron S Sportback"),
    ("E-Tron Sportback", "E-Tron Sportback"),
    ("NSU RO 80", "NSU RO 80"),
    ("Q2", "Q2"),
    ("Q3", "Q3"),
    ("Q3 Sportback", "Q3 Sportback"),
    ("Q4 e-tron", "Q4 e-tron"),
    ("Q5", "Q5"),
    ("Q5 Sportback", "Q5 Sportback"),
    ("Q7", "Q7"),
    ("Q8", "Q8"),
    ("Quattro", "Quattro"),
    ("R8", "R8"),
    ("R8 LMP", "R8 LMP"),
    ("RS 2", "RS 2"),
    ("RS 3", "RS 3"),
    ("RS 4", "RS 4"),
    ("RS 5", "RS 5"),
    ("RS 6", "RS 6"),
    ("RS 7", "RS 7"),
    ("RS Q3", "RS Q3"),
    ("RS Q3 Sportback", "RS Q3 Sportback"),
    ("RS Q8", "RS Q8"),
    ("S1", "S1"),
    ("S2", "S2"),
    ("S3", "S3"),
    ("S4", "S4"),
    ("S5", "S5"),
    ("S6", "S6"),
    ("S7", "S7"),
    ("S8", "S8"),
    ("SQ2", "SQ2"),
    ("SQ5", "SQ5"),
    ("SQ5 Sportback", "SQ5 Sportback"),
    ("SQ7", "SQ7"),
    ("SQ8", "SQ8"),
    ("TT", "TT"),
    ("TT RS", "TT RS"),
    ("TTS", "TTS"),
    ("Typ R", "Typ R"),
    ("V8", "V8"),

    # Alfa Romeo
    ("145", "145"),
    ("146", "146"),
    ("147", "147"),
    ("155", "155"),
    ("156", "156"),
    ("159", "159"),
    ("164", "164"),
    ("166", "166"),
    ("33", "33"),
    ("GT", "GT"),
    ("Mito", "Mito"),
    ("Stelvio", "Stelvio"),

    # Alpina
    ("B3", "B3"),
    ("B5", "B5"),
    ("B7", "B7"),
    ("D5", "D5"),

    # ARO



    # BMW
    ("02 (E10)", "02 (E10)"),
    ("1 Серии", "1 Серии"),
    ("1M", "1M"),
    ("2 Серии", "2 Серии"),
    ("2 Серии A", "2 Серии A"),
    ("2 Серии G", "2 Серии G"),
    ("2000 C/Cs", "2000 C/Cs"),
    ("3 Серии", "3 Серии"),
    ("3/15", "3/15"),
    ("315", "315"),
    ("3200", "3200"),
    ("321", "321"),
    ("326", "326"),
    ("327", "327"),
    ("340", "340"),
    ("4 Серии", "4 Серии"),
    ("5 Серии", "5 Серии"),
    ("501", "501"),
    ("502", "502"),
    ("503", "503"),
    ("507", "507"),
    ("6 Серии", "6 Серии"),
    ("600", "600"),
    ("7 Серии", "7 Серии"),
    ("700", "700"),
    ("8 Серии", "8 Серии"),
    ("E3", "E3"),
    ("E9", "E9"),
    ("M2", "M2"),
    ("M3", "M3"),
    ("M4", "M4"),
    ("M5", "M5"),
    ("M6", "M6"),
    ("M8", "M8"),
    ("New Class", "New Class"),
    ("X1", "X1"),
    ("X2", "X2"),
    ("X3", "X3"),
    ("X3 M", "X3 M"),
    ("X4", "X4"),
    ("X4 M", "X4 M"),
    ("X5", "X5"),
    ("X5 M", "X5 M"),
    ("X6", "X6"),
    ("X6 M", "X6 M"),
    ("X7", "X7"),
    ("XM", "XM"),
    ("Z1", "Z1"),
    ("Z3", "Z3"),
    ("Z3 M", "Z3 M"),
    ("Z4", "Z4"),
    ("Z4 M", "Z4 M"),
    ("Z8", "Z8"),
    ("i3", "i3"),
    ("i4", "i4"),
    ("i8", "i8"),
    ("iX", "iX"),
    ("iX3", "iX3"),

    # Mercedes-Benz
    ("190 (W201)", "190 (W201)"),
    ("190 SL", "190 SL"),
    ("A-Класс", "A-Класс"),
    ("A-Класс AMG", "A-Класс AMG"),
    ("AMG GT", "AMG GT"),
    ("B-Класс", "B-Класс"),
    ("C-Класс", "C-Класс"),
    ("C-Класс AMG", "C-Класс AMG"),
    ("CL-Класс", "CL-Класс"),
    ("CL-Класс AMG", "CL-Класс AMG"),
    ("CLA", "CLA"),
    ("CLA AMG", "CLA AMG"),
    ("CLC-Класс", "CLC-Класс"),
    ("CLK-Класс", "CLK-Класс"),
    ("CLK-Класс AMG", "CLK-Класс AMG"),
    ("CLS", "CLS"),
    ("CLS AMG", "CLS AMG"),
    ("Citan", "Citan"),
    ("E-Класс", "E-Класс"),
    ("E-Класс AMG", "E-Класс AMG"),
    ("EQA", "EQA"),
    ("EQC", "EQC"),
    ("EQE", "EQE"),
    ("EQS", "EQS"),
    ("EQS SUV", "EQS SUV"),
    ("EQV", "EQV"),
    ("G-Класс", "G-Класс"),
    ("G-Класс AMG", "G-Класс AMG"),
    ("G-Класс AMG 6x6", "G-Класс AMG 6x6"),
    ("GL-Класс", "GL-Класс"),
    ("GL-Класс AMG", "GL-Класс AMG"),
    ("GLA", "GLA"),
    ("GLA AMG", "GLA AMG"),
    ("GLB", "GLB"),
    ("GLB AMG", "GLB AMG"),
    ("GLC", "GLC"),
    ("GLC AMG", "GLC AMG"),
    ("GLC Coupe", "GLC Coupe"),
    ("GLC Coupe AMG", "GLC Coupe AMG"),
    ("GLE", "GLE"),
    ("GLE AMG", "GLE AMG"),
    ("GLE Coupe", "GLE Coupe"),
    ("GLE Coupe AMG", "GLE Coupe AMG"),
    ("GLK-Класс", "GLK-Класс"),
    ("GLS", "GLS"),
    ("GLS AMG", "GLS AMG"),
    ("M-Класс", "M-Класс"),
    ("M-Класс AMG", "M-Класс AMG"),
    ("MB", "MB"),
    ("Maybach G 650 Landaulet", "Maybach G 650 Landaulet"),
    ("Maybach GLS", "Maybach GLS"),
    ("Maybach S-Класс", "Maybach S-Класс"),
    ("Metris", "Metris"),
    ("R-Класс", "R-Класс"),
    ("R-Класс AMG", "R-Класс AMG"),
    ("S-Класс", "S-Класс"),
    ("S-Класс AMG", "S-Класс AMG"),
    ("SL", "SL"),
    ("SL AMG", "SL AMG"),
    ("SLC", "SLC"),
    ("SLC AMG", "SLC AMG"),
    ("SLK", "SLK"),
    ("SLK-Класс AMG", "SLK-Класс AMG"),
    ("SLR Mclaren", "SLR Mclaren"),
    ("SLS AMG", "SLS AMG"),
    ("Simplex", "Simplex"),
    ("V-Класс", "V-Класс"),
    ("Vaneo", "Vaneo"),
    ("Viano", "Viano"),
    ("Vito", "Vito"),
    ("W100", "W100"),
    ("W105", "W105"),
    ("W108", "W108"),
    ("W110", "W110"),
    ("W111", "W111"),
    ("W114", "W114"),
    ("W115", "W115"),
    ("W120", "W120"),
    ("W121", "W121"),
    ("W123", "W123"),
    ("W124", "W124"),
    ("W128", "W128"),
    ("W136", "W136"),
    ("W142", "W142"),
    ("W186", "W186"),
    ("W188", "W188"),
    ("W189", "W189"),
    ("W191", "W191"),
    ("W29", "W29"),
]   # модели авто
CAR_COLOR = [
    ('Белый', 'Белый'),
    ('Бордовый', 'Бордовый'),
    ('Жёлтый', 'Жёлтый'),
    ('Зелёный', 'Зелёный'),
    ('Коричневый', 'Коричневый'),
    ('Красный', 'Красный'),
    ('Оранжевый', 'Оранжевый'),
    ('Серебристый', 'Серебристый'),
]   # Цвет
CAR_BODY_TYPE = [
    ('Седан', 'Седан'),
    ('Универсал', 'Универсал'),
    ('Хэтчбек', 'Хэтчбек'),
    ('Минивэн', 'Минивэн '),
    ('Внедорожник', 'Внедорожник'),
    ('Купе', 'Купе'),
    ('Кабриолет', 'Кабриолет'),
    ('Микроавтобус', 'Микроавтобус'),
    ('Фургон', 'Фургон'),
    ('Пикап', 'Пикап'),
    ('Лимузин', 'Лимузин'),
    ('Лифтбек', 'Лифтбек'),
]   # Тип кузова
CAR_ENGIN_TYPE = [
    ('Бензин', 'Бензин'),
    ('Бензин (пропан-бутан)', 'Бензин (пропан-бутан)'),
    ('Бензин (метан)', 'Бензин (метан)'),
    ('Бензин (гибрид)', 'Бензин (гибрид)'),
    ('Дизель', 'Дизель'),
    ('Дизель (гибрид)', 'Дизель (гибрид)'),
    ('Электричество', 'Электричество'),
]   # Тип двигателя
CAR_DRIVE_UNIT = [
    ('Передний', 'Передний'),
    ('Задний', 'Задний'),
    ('Полный', 'Полный'),
]   # Привод
CAR_TRANSMISSION = [
    ('Автоматическая (автомат)', 'Автоматическая (автомат)'),
    ('Автоматическая (робот)', 'Автоматическая (робот)'),
    ('Автоматическая (вариатор)', 'Автоматическая (вариатор)'),
    ('Механика', 'Механика'),
]   # Коробка передач
CAR_ENGINE_VOLUME = [
    ('1.0 л', '1.0 л'),
    ('1.1 л', '1.1 л'),
    ('1.2 л', '1.2 л'),
    ('1.3 л', '1.3 л'),
    ('1.4 л', '1.4 л'),
    ('1.5 л', '1.5 л'),
    ('1.6 л', '1.6 л'),
    ('1.7 л', '1.7 л'),
    ('1.8 л', '1.8 л'),
    ('1.9 л', '1.9 л'),
    ('2.0 л', '2.0 л'),
    ('2.1 л', '2.1 л'),
    ('2.2 л', '2.2 л'),
    ('2.3 л', '2.3 л'),
    ('2.4 л', '2.4 л'),
    ('2.5 л', '2.5 л'),
    ('2.6 л', '2.6 л'),
    ('2.7 л', '2.7 л'),
    ('2.8 л', '2.8 л'),
    ('2.9 л', '2.9 л'),
    ('3.0 л', '3.0 л'),
    ('3.2 л', '3.2 л'),
    ('3.3 л', '3.3 л'),
    ('3.5 л', '3.5 л'),
    ('3.6 л', '3.6 л'),
    ('3.7 л', '3.7 л'),
    ('3.8 л', '3.8 л'),
    ('3.9 л', '3.9 л'),
    ('4.0 л', '4.0 л'),
    ('> 4.0 л', ' > 4.0 л'),
]   # Объём двигателя
CAR_YEAR = [
    ('2023', '2023'),
    ('2022', '2022'),
    ('2021', '2021'),
    ('2020', '2020'),
    ('2019', '2019'),
    ('2018', '2018'),
    ('2017', '2017'),
    ('2016', '2016'),
    ('2015', '2015'),
    ('2014', '2014'),
    ('2013', '2013'),
    ('2012', '2012'),
    ('2011', '2011'),
    ('2010', '2010'),
    ('2009', '2009'),
    ('2008', '2008'),
    ('2007', '2007'),
    ('2006', '2006'),
    ('2005', '2005'),
    ('2004', '2004'),
    ('2003', '2003'),
    ('2002', '2002'),
    ('2001', '2001'),
    ('2000', '2000'),
    ('1999', '1999'),
    ('1998', '1998'),
    ('1997', '1997'),
    ('1996', '1996'),
    ('1995', '1995'),
    ('1994', '1994'),
    ('1993', '1993'),
    ('1992', '1992'),
    ('1991', '1991'),
    ('1990', '1990'),
    ('1989', '1989'),
    ('1988', '1988'),
    ('1987', '1987'),
    ('1986', '1986'),
    ('1985', '1985'),
    ('1984', '1984'),
    ('1983', '1983'),
    ('1982', '1982'),
    ('1981', '1981'),
    ('1980 или ранее', '1980 или ранее'),
]   # Год выпуска
CAR_STATE = [
    ('С пробегом', 'С пробегом'),
    ('Новый', 'Новый'),
]   # Состояние авто
CAR_INTERIOR_MATERIAL = [
    ('натуральная кожа', 'натуральная кожа'),
    ('искусственная кожа', 'искусственная кожа'),
    ('ткань', 'ткань'),
    ('велюр', 'велюр'),
    ('алькантара', 'алькантара'),
    ('комбинированные материалы', 'комбинированные материалы'),
]
CAR_INTERIOR_COLOR = [
    ('светлый', 'светлый'),
    ('комби', 'комби'),
    ('тёмный', 'тёмный'),
]
CAR_REG_COUNTRY = [
    ('Беларусь', 'Беларусь'),
    ('Россия', 'Россия'),
    ('Другая страна', 'Другая страна'),
]
CAR_ACCOUNTING = [
    ('на учёте в ГАИ', 'на учёте в ГАИ'),
    ('снят с учёта', 'снят с учёта'),
]

###### ГРУЗОВЫЕ АВТО И АВТОБУСЫ ######
TRUCK_BRAND = [
    ("ASTRA", "ASTRA"),
    ("Asia", "Asia"),
    ("Autosan", "Autosan"),
    ("Avia", "Avia"),
    ("BAW", "BAW"),
    ("Beifang Benchi", "Beifang Benchi"),
    ("Bova", "Bova"),
    ("CAMC", "CAMC"),
    ("Changan", "Changan"),
    ("Citroen", "Citroen"),
    ("DAF", "DAF"),
    ("Daewoo", "Daewoo"),
    ("Daihatsu", "Daihatsu"),
    ("DongFeng", "DongFeng"),
    ("EOS", "EOS"),
    ("Evobus", "Evobus"),
    ("FAW", "FAW"),
    ("Fiat", "Fiat"),
    ("Ford", "Ford"),
    ("Foton", "Foton"),
    ("Foxbus", "Foxbus"),
    ("Freightliner", "Freightliner"),
    ("GMC", "GMC"),
    ("Golden Dragon", "Golden Dragon"),
    ("Hania", "Hania"),
    ("Higer", "Higer"),
    ("Hino", "Hino"),
    ("Howo", "Howo"),
    ("Hyundai", "Hyundai"),
    ("IFA", "IFA"),
    ("Ikarus", "Ikarus"),
    ("International", "International"),
    ("Irisbus", "Irisbus"),
    ("Isuzu", "Isuzu"),
    ("Iveco", "Iveco"),
    ("JAC", "JAC"),
    ("JMC", "JMC"),
    ("Kenworth", "Kenworth"),
    ("Kia", "Kia"),
    ("King Long", "King Long"),
    ("MAN", "MAN"),
    ("Mack", "Mack"),
    ("Magirus", "Magirus"),
    ("Marcopolo", "Marcopolo"),
    ("Mazda", "Mazda"),
    ("Mercedes", "Mercedes"),
    ("Mitsubishi", "Mitsubishi"),
    ("Mudan", "Mudan"),
    ("Naveco", "Naveco"),
    ("Neoplan", "Neoplan"),
    ("Nissan", "Nissan"),
    ("Nysa", "Nysa"),
    ("Opel", "Opel"),
    ("Otokar", "Otokar"),
    ("Otoyol", "Otoyol"),
    ("Peterbilt", "Peterbilt"),
    ("Peugeot", "Peugeot"),
    ("Renault", "Renault"),
    ("Robur", "Robur"),
    ("SOR Libchavy", "SOR Libchavy"),
    ("Sanos", "Sanos"),
    ("Scania", "Scania"),
    ("Setra", "Setra"),
    ("Shacman (Shaanxi)", "Shacman (Shaanxi)"),
    ("ShenLong (Sunlong)", "ShenLong (Sunlong)"),
    ("Shuchi", "Shuchi"),
    ("Silant", "Silant"),
    ("Simaz", "Simaz"),
    ("Sisu", "Sisu"),
    ("Sitrak", "Sitrak"),
    ("Solaris", "Solaris"),
    ("SsangYong", "SsangYong"),
    ("Sterling", "Sterling"),
    ("Steyr", "Steyr"),
    ("TAM", "TAM"),
    ("TATA", "TATA"),
    ("Tatra", "Tatra"),
    ("Temsa", "Temsa"),
    ("Tiema", "Tiema"),
    ("Toyota", "Toyota"),
    ("Van Hool", "Van Hool"),
    ("Volgabus", "Volgabus"),
    ("Volkswagen", "Volkswagen"),
    ("Volvo", "Volvo"),
    ("WAW", "WAW"),
    ("Yuejin", "Yuejin"),
    ("Yutong", "Yutong"),
    ("Zhong Tong", "Zhong Tong"),
    ("Zuk", "Zuk"),
    ("Автотор", "Автотор"),
    ("БАЗ", "БАЗ"),
    ("БЕЛА", "БЕЛА"),
    ("БЗКТ", "БЗКТ"),
    ("БелАЗ", "БелАЗ"),
    ("Богдан", "Богдан"),
    ("ВИС", "ВИС"),
    ("Вездеходы ГВА", "Вездеходы ГВА"),
    ("Воложанин", "Воложанин"),
    ("ГАЗ", "ГАЗ"),
    ("ГАЗ-САЗ", "ГАЗ-САЗ"),
    ("ЗиЛ", "ЗиЛ"),
    ("Иж", "Иж"),
    ("КАЗ", "КАЗ"),
    ("КЗКТ", "КЗКТ"),
    ("КаВЗ", "КаВЗ"),
    ("КамАЗ", "КамАЗ"),
    ("КрАЗ", "КрАЗ"),
    ("ЛАЗ", "ЛАЗ"),
    ("ЛИАЗ", "ЛИАЗ"),
    ("Люблин", "Люблин"),
    ("МАЗ", "МАЗ"),
    ("МАЗ-МАН", "МАЗ-МАН"),
    ("МАРЗ", "МАРЗ"),
    ("МЗКТ", "МЗКТ"),
    ("Неман", "Неман"),
    ("НефаЗ", "НефаЗ"),
    ("ПАЗ", "ПАЗ"),
    ("СААЗ", "СААЗ"),
    ("САРЗ", "САРЗ"),
    ("Тонар", "Тонар"),
    ("УАЗ", "УАЗ"),
    ("Урал", "Урал"),
    ("УралАЗ", "УралАЗ"),
    ("ЯРОВИТ МОТОРС", "ЯРОВИТ МОТОРС"),
    ("Яровит", "Яровит"),
    ("Другая", "Другая"),
]   # марки грузовиков
TRUCK_TYPE = [
    ('Полуприцеп', 'Полуприцеп'),
    ('Рефрижератор', 'Рефрижератор'),
    ('Контейнеровоз', 'Контейнеровоз'),
    ('Открытая бортовая', 'Открытая бортовая'),
    ('Открытая платформа', 'Открытая платформа'),
    ('Автоцистерна', 'Автоцистерна'),
    ('Автовоз', 'Автовоз'),
    ('Зерновоз', 'Зерновоз'),
    ('Самосвал', 'Самосвал'),
    ('Лесовоз', 'Лесовоз'),
    ('Автосцепка', 'Автосцепка'),
    ('Фургон', 'Фургон'),
    ('Изотерм', 'Изотерм'),
    ('Седельный тягач', 'Седельный тягач'),
    ('Автобус', 'Автобус'),
]   # тип грузовика
TRUCK_LOAD_CAPACITY = [
    ('< 3 т', '< 3 т'),
    ('3 т', '3 т'),
    ('4 т', '4 т'),
    ('5 т', '5 т'),
    ('6 т', '6 т'),
    ('7 т', '7 т'),
    ('8 т', '8 т'),
    ('9 т', '9 т'),
    ('10 т', '10 т'),
    ('11 т', '11 т'),
    ('12 т', '12 т'),
    ('13 т', '13 т'),
    ('14 т', '14 т'),
    ('15 т', '15 т'),
    ('16 т', '16 т'),
    ('17 т', '17 т'),
    ('18 т', '18 т'),
    ('19 т', '19 т'),
    ('20 т', '20 т'),
    ('> 20 т', '> 20 т'),
]   # грузоподъёмность
TRUCK_TRANSMISSION = [
    ('Автоматическая', 'Автоматическая'),
    ('Механическая', 'Механическая'),
]   # тип коробки передач

###### МОТОЦИКЛЫ ######
MOTOBIKE_TYPE = [
    ('Кастом', 'Кастом'),
    ('Классик', 'Классик'),
    ('Кроссовый', 'Кроссовый'),
    ('Круизер/Чоппер', 'Круизер/Чоппер'),
    ('Мотард', 'Мотард'),
    ('Пит-байк', 'Пит-байк'),
    ('Спорт', 'Спорт'),
    ('Спорт-турист', 'Спорт-турист'),
    ('Стрит', 'Стрит'),
    ('Трайк', 'Трайк'),
    ('Туризм', 'Туризм'),
    ('Эндуро', 'Эндуро'),
]   # тип мотоцикла
MOTOBIKE_BRAND = [
    ("Apollo", "Apollo"),
    ("Aprilia", "Aprilia"),
    ("Avantis", "Avantis"),
    ("BAJAJ", "BAJAJ"),
    ("BMW", "BMW"),
    ("BSA", "BSA"),
    ("BSE", "BSE"),
    ("Baltmotors", "Baltmotors"),
    ("Benelli", "Benelli"),
    ("Beta", "Beta"),
    ("Bimota", "Bimota"),
    ("Bombardier", "Bombardier"),
    ("Boss Hoss", "Boss Hoss"),
    ("Buell", "Buell"),
    ("CFMoto", "CFMoto"),
    ("CZ", "CZ"),
    ("Cagiva", "Cagiva"),
    ("Can-Am", "Can-Am"),
    ("Carver", "Carver"),
    ("Cezet", "Cezet"),
    ("Cronus", "Cronus"),
    ("Customs", "Customs"),
    ("DKW", "DKW"),
    ("Daelim", "Daelim"),
    ("Dodge", "Dodge"),
    ("Ducati", "Ducati"),
    ("Falcon", "Falcon"),
    ("GR", "GR"),
    ("GX moto", "GX moto"),
    ("Gas Gas", "Gas Gas"),
    ("Gilera", "Gilera"),
    ("Guowei", "Guowei"),
    ("Harley-Davidson", "Harley-Davidson"),
    ("Honda", "Honda"),
    ("Hors", "Hors"),
    ("Husqvarna", "Husqvarna"),
    ("Hyosung", "Hyosung"),
    ("Indian", "Indian"),
    ("IRBIS", "IRBIS"),
    ("JMC", "JMC"),
    ("Jaguar", "Jaguar"),
    ("Jawa", "Jawa"),
    ("Jieda", "Jieda"),
    ("KTM", "KTM"),
    ("KXD", "KXD"),
    ("Kawasaki", "Kawasaki"),
    ("KAYO", "KAYO"),
    ("Kymco", "Kymco"),
    ("LEM", "LEM"),
    ("Laverda", "Laverda"),
    ("Lifan", "Lifan"),
    ("Loncin", "Loncin"),
    ("MV Agusta", "MV Agusta"),
    ("MZ", "MZ"),
    ("Megelli", "Megelli"),
    ("Mikilon", "Mikilon"),
    ("Moto Guzzi", "Moto Guzzi"),
    ("Moto Morini", "Moto Morini"),
    ("Motoland", "Motoland"),
    ("Nitro", "Nitro"),
    ("Norton", "Norton"),
    ("Orion", "Orion"),
    ("Pannonia", "Pannonia"),
    ("Pitster Pro", "Pitster Pro"),
    ("Polini", "Polini"),
    ("PWR Racing", "PWR Racing"),
    ("Qingqi", "Qingqi"),
    ("Racer", "Racer"),
    ("Regulmoto", "Regulmoto"),
    ("Roliz", "Roliz"),
    ("Royal Enfield", "Royal Enfield"),
    ("S2 Motors", "S2 Motors"),
    ("Sachs", "Sachs"),
    ("Sherco", "Sherco"),
    ("Skyline", "Skyline"),
    ("Sonik", "Sonik"),
    ("Stalker", "Stalker"),
    ("Stels", "Stels"),
    ("Suzuki", "Suzuki"),
    ("TM Racing", "TM Racing"),
    ("Triumph", "Triumph"),
    ("Ural Motors", "Ural Motors"),
    ("Victory", "Victory"),
    ("Viper", "Viper"),
    ("Voxan", "Voxan"),
    ("Wels", "Wels"),
    ("Xmotos", "Xmotos"),
    ("Yamasaki", "Yamasaki"),
    ("YCF", "YCF"),
    ("Yamaha", "Yamaha"),
    ("ZIP Motors", "ZIP Motors"),
    ("Znen", "Znen"),
    ("Zongshen", "Zongshen"),
    ("Zundapp", "Zundapp"),
    ("Zuum", "Zuum"),
    ("Авторос", "Авторос"),
    ("Восход", "Восход"),
    ("ГАЗ", "ГАЗ"),
    ("Днепр", "Днепр"),
    ("ЗиД", "ЗиД"),
    ("ИЖ", "ИЖ"),
    ("Ковровец", "Ковровец"),
    ("Львовский мотозавод", "Львовский мотозавод"),
    ("ММ", "ММ"),
    ("Минск (Minsk)", "Минск (Minsk)"),
    ("ТМЗ", "ТМЗ"),
    ("Трэкол", "Трэкол"),
    ("Урал", "Урал"),
    ("Другая", "Другая"),
]  # марки мотоциклов
MOTOBILE_DRIVE_UNIT = [
    ('Кардан', 'Кардан'),
    ('Ремень', 'Ремень'),
    ('Цепь', 'Цепь'),
]   # привод
MOTOBIKE_NUMBER_CYCLES = [
    ("2", "2"),
    ("4", "4"),
]   # число тактов
MOTOBIKE_NUMBER_CYLINDERS = [
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
    ("6", "6"),
]   # количество цилиндров
MOTOVIKE_VOLUME = [
    ('16', '16'),
    ('40', '40'),
    ('48', '48'),
    ('49', '49'),
    ('50', '50'),
    ('60', '60'),
    ('64', '64'),
    ('70', '70'),
    ('72', '72'),
    ('84', '84'),
    ('97', '97'),
    ('99', '99'),
    ('100', '100'),
    ('107', '107'),
    ('110', '110'),
    ('112', '112'),
    ('123', '123'),
    ('124', '124'),
    ('125', '125'),
    ('140', '140'),
    ('145', '145'),
    ('149', '149'),
    ('150', '150'),
    ('158', '158'),
    ('160', '160'),
    ('190', '190'),
    ('196', '196'),
    ('197', '197'),
    ('198', '198'),
    ('200', '200'),
    ('210', '210'),
    ('220', '220'),
    ('223', '223'),
    ('224', '224'),
    ('225', '225'),
    ('233', '233'),
    ('249', '249'),
    ('250', '250'),
    ('270', '270'),
    ('271', '271'),
    ('275', '275'),
    ('279', '279'),
    ('298', '298'),
    ('300', '300'),
    ('313', '313'),
    ('321', '321'),
    ('350', '350'),
    ('352', '352'),
    ('373', '373'),
    ('399', '399'),
    ('400', '400'),
    ('449', '449'),
    ('450', '450'),
    ('471', '471'),
    ('493', '493'),
    ('495', '495'),
    ('499', '499'),
    ('500', '500'),
    ('550', '550'),
    ('570', '570'),
    ('580', '580'),
    ('600', '600'),
    ('636', '636'),
    ('649', '649'),
    ('650', '650'),
    ('689', '689'),
    ('695', '695'),
    ('700', '700'),
    ('749', '749'),
    ('750', '750'),
    ('800', '800'),
    ('847', '847'),
    ('900', '900'),
    ('942', '942'),
    ('948', '948'),
    ('976', '976'),
    ('998', '998'),
    ('1000', '1000'),
    ('1043', '1043'),
    ('1200', '1200'),
    ('1298', '1298'),
    ('1500', '1500'),
    ('1679', '1679'),
    ('2000', '2000'),
    ('2500', '2500'),
]   # объём, см³

###### КВАРТИРЫ ######
APARTMENT_DEAL_TYPE = [
    ('Продажа', 'Продажа'),
    ('Сдача', 'Сдача'),
]   # тип сделки
APARTMENT_ROOMS = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5 и более', '5 и более'),
]   # количество комнат
APARTMENT_LAYOUT = [
    ('Свободная планировка', 'Свободная планировка'),
    ('Студия', 'Студия'),
]    # вид планировки
APARTMENT_FLOORS = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
    ('> 30', '> 30'),
]   # этаж
APARTMENT_CEILING_HEIGHT = [
    ('от 2.5 м', 'от 2.5 м'),
    ('от 2.7 м', 'от 2.7 м'),
    ('от 3 м', 'от 3 м'),
    ('от 3.5 м', 'от 3.5 м'),
    ('от 4 м', 'от 4 м'),
]   # высота потолков
APARTMENT_WALL_MATERIAL = [
    ('Панельный', 'Панельный'),
    ('Монолитный', 'Монолитный'),
    ('Кирпичный', 'Кирпичный'),
    ('Блочный', 'Блочный'),
    ('Каркасный', 'Каркасный'),
    ('Каркасно-блочный', 'Каркасно-блочный'),
]   # материал стен
APARTMENT_SALESMAN = [
    ('Собственник', 'Собственник'),
    ('Агент/Застройщик', 'Агент/Застройщик'),
]   # продавец

###### АУДИОТЕХНИКА ######
AUDIO_TYPE = [
    ('CD', 'CD'),
    ('MP3-плееры', 'MP3-плееры'),
    ('Акустика Hi-Fi и Hi-End', 'Акустика Hi-Fi и Hi-End'),
    ('Беспроводные и портативные колонки', 'Беспроводные и портативные колонки'),
    ('Кабели и адаптеры', 'Кабели и адаптеры'),
    ('Микрофоны', 'Микрофоны'),
    ('Музыкальные центры', 'Музыкальные центры'),
    ('Сделано в СССР', 'Сделано в СССР'),
    ('Радиоприемники', 'Радиоприемники'),
    ('Радиодетали', 'Радиодетали'),
    ('Усилители и ресиверы', 'Усилители и ресиверы'),
    ('Аксессуары для аудио', 'Аксессуары для аудио'),
    ('Прочее', 'Прочее'),
]   # тип
AUDIO_STATE = [
    ('Новое', 'Новое'),
    ('Б/у', 'Б/у'),
]   # состояние

###### НАУШНИКИ ######
HEADPHONES_TYPE = [
    ('Внутриканальные', 'Внутриканальные'),
    ('Вкладыши', 'Вкладыши'),
    ('Накладные', 'Накладные'),
    ('Полноразмерные', 'Полноразмерные'),
]   # тип
HEADPHONES_BRAND = [
    ("1More", "1More"),
    ("2E", "2E"),
    ("A4Tech", "A4Tech"),
    ("ACME", "ACME"),
    ("AKG", "AKG"),
    ("Anker", "Anker"),
    ("Apple", "Apple"),
    ("ASUS", "ASUS"),
    ("Atomic", "Atomic"),
    ("Audeze", "Audeze"),
    ("Audio-Technica", "Audio-Technica"),
    ("Awei", "Awei"),
    ("Axtel", "Axtel"),
    ("Bang &amp; Olufsen", "Bang &amp; Olufsen"),
    ("Baseus", "Baseus"),
    ("BBK", "BBK"),
    ("Beats", "Beats"),
    ("Beyerdynamic", "Beyerdynamic"),
    ("Blast", "Blast"),
    ("Borofone", "Borofone"),
    ("Bose", "Bose"),
    ("BQ", "BQ"),
    ("Brainwavz", "Brainwavz"),
    ("Canyon", "Canyon"),
    ("Celebrat", "Celebrat"),
    ("Corsair", "Corsair"),
    ("Cougar", "Cougar"),
    ("Creative", "Creative"),
    ("CrownMicro", "CrownMicro"),
    ("D&amp;A", "D&amp;A"),
    ("Defender", "Defender"),
    ("Dialog", "Dialog"),
    ("Digma", "Digma"),
    ("Dunu", "Dunu"),
    ("Edifier", "Edifier"),
    ("Elari", "Elari"),
    ("Eltronic", "Eltronic"),
    ("Evolution", "Evolution"),
    ("EXPERTS", "EXPERTS"),
    ("Freestyle", "Freestyle"),
    ("GAL", "GAL"),
    ("Gembird", "Gembird"),
    ("Genesis", "Genesis"),
    ("Genius", "Genius"),
    ("Harper", "Harper"),
    ("Haylou", "Haylou"),
    ("Hiper", "Hiper"),
    ("Hoco", "Hoco"),
    ("HONOR", "HONOR"),
    ("HP", "HP"),
    ("Huawei", "Huawei"),
    ("HyperX", "HyperX"),
    ("InterStep", "InterStep"),
    ("Jabra", "Jabra"),
    ("JBL", "JBL"),
    ("Jet.A", "Jet.A"),
    ("JVC", "JVC"),
    ("KOSS", "KOSS"),
    ("KZ Acoustics", "KZ Acoustics"),
    ("LG", "LG"),
    ("Logitech", "Logitech"),
    ("Marshall", "Marshall"),
    ("Marvo", "Marvo"),
    ("Master &amp; Dynamic", "Master &amp; Dynamic"),
    ("MEIZU", "MEIZU"),
    ("Microlab", "Microlab"),
    ("Microsoft", "Microsoft"),
    ("Motorola", "Motorola"),
    ("Nobby", "Nobby"),
    ("Nokia", "Nokia"),
    ("Oklick", "Oklick"),
    ("Olmio", "Olmio"),
    ("Omega", "Omega"),
    ("Oppo", "Oppo"),
    ("Padmate", "Padmate"),
    ("Panasonic", "Panasonic"),
    ("Perfeo", "Perfeo"),
    ("Philips", "Philips"),
    ("Pioneer", "Pioneer"),
    ("Platinet", "Platinet"),
    ("QCY", "QCY"),
    ("QUMO", "QUMO"),
    ("Razer", "Razer"),
    ("Realme", "Realme"),
    ("Red Line", "Red Line"),
    ("Redragon", "Redragon"),
    ("Ritmix", "Ritmix"),
    ("Rombica", "Rombica"),
    ("Sabbat", "Sabbat"),
    ("Samsung", "Samsung"),
    ("SBOX", "SBOX"),
    ("Sennheiser", "Sennheiser"),
    ("Shure", "Shure"),
    ("Skullcandy", "Skullcandy"),
    ("Smart Buy", "Smart Buy"),
    ("Sony", "Sony"),
    ("Soul", "Soul"),
    ("SoundMagic", "SoundMagic"),
    ("SteelSeries", "SteelSeries"),
    ("SVEN", "SVEN"),
    ("TCL", "TCL"),
    ("TFN", "TFN"),
    ("TFZ", "TFZ"),
    ("TRN", "TRN"),
    ("Urbanears", "Urbanears"),
    ("Vsonic", "Vsonic"),
    ("White Shark", "White Shark"),
    ("WiWU", "WiWU"),
    ("Xiaomi", "Xiaomi"),
    ("Yison", "Yison"),
    ("Другой", "Другой"),
]   # производитель наушников
HEADPHONES_CONNECTOR = [
    ('3.5 мм', '3.5 мм'),
    ('2x3.5 мм', '2x3.5 мм'),
    ('USB Type-A', 'USB Type-A'),
    ('USB Type-C', 'USB Type-C'),
    ('Lightning', 'Lightning'),
    ('6.3 мм', '6.3 мм'),
    ('microUSB', 'microUSB'),
]   # тип разъёма наушников
HEADPHONES_PURPOSE = [
    ('Игровые', 'Игровые'),
    ('Спортивные', 'Спортивные'),
    ('Мониторные', 'Мониторные'),
    ('Для DJ', 'Для DJ'),
    ('Детские', 'Детские'),
    ('Без специализации', 'Без специализации'),
]   # назначение
HEADPHONES_FASTENING = [
    ('Внутри уха', 'Внутри уха'),
    ('Оголовье', 'Оголовье'),
    ('Затылочная дужка', 'Затылочная дужка'),
    ('Заушное крепление', 'Заушное крепление'),
    ('На шее', 'На шее'),
]   # крепление

###### ТВ И ВИДЕОТЕХНИКА ######
VIDEO_EQUIPMENT_TYPE = [
    ("Выберите", "Выберите"),
    ("Телевизоры", "Телевизоры"),
    ("Видео, DVD и Blu-ray плееры", "Видео, DVD и Blu-ray плееры"),
    ("Видеокамеры", "Видеокамеры"),
    ("Проекторы", "Проекторы"),
    ("Спутниковые ресиверы", "Спутниковые ресиверы"),
    ("ТВ-тюнеры", "ТВ-тюнеры"),
    ("Аксессуары для ТВ и видео", "Аксессуары для ТВ и видео"),
    ("Прочее", "Прочее"),
]   # тип ТВ и видеотехники
VIDEO_EQUIPMENT_BRAND = [
    # Телевизоры
    ("Витязь", "Витязь"),
    ("AKAI", "AKAI"),
    ("BBK", "BBK"),
    ("BEKO", "BEKO"),
    ("Blaupunkt", "Blaupunkt"),
    ("BQ", "BQ"),
    ("DEXP", "DEXP"),
    ("Erisson", "Erisson"),
    ("Funai", "Funai"),
    ("GoldStar", "GoldStar"),
    ("Grundig", "Grundig"),
    ("Haier", "Haier"),
    ("Hitachi", "Hitachi"),
    ("Horizont", "Horizont"),
    ("Hyundai", "Hyundai"),
    ("iFFALCON", "iFFALCON"),
    ("Izumi", "Izumi"),
    ("JVC", "JVC"),
    ("KIVI", "KIVI"),
    ("LG", "LG"),
    ("Mystery", "Mystery"),
    ("Panasonic", "Panasonic"),
    ("Philips", "Philips"),
    ("Polar", "Polar"),
    ("Polarline", "Polarline"),
    ("Rolsen", "Rolsen"),
    ("Rubin", "Rubin"),
    ("Samsung", "Samsung"),
    ("Sharp", "Sharp"),
    ("Shivaki", "Shivaki"),
    ("Sony", "Sony"),
    ("Supra", "Supra"),
    ("TCL", "TCL"),
    ("TELEFUNKEN", "TELEFUNKEN"),
    ("Thomson", "Thomson"),
    ("Toshiba", "Toshiba"),
    ("VITEK", "VITEK"),
    ("Xiaomi", "Xiaomi"),
    ("Другой", "Другой"),

    # Видео, DVD и Blu-ray плееры
    ("AKAI", "AKAI"),
    ("Arcam", "Arcam"),
    ("BBK", "BBK"),
    ("Cambridge Audio", "Cambridge Audio"),
    ("Denon", "Denon"),
    ("Erisson", "Erisson"),
    ("FUSION Electronics", "FUSION Electronics"),
    ("Harman/Kardon", "Harman/Kardon"),
    ("Horizont", "Horizont"),
    ("Hyundai", "Hyundai"),
    ("Integra", "Integra"),
    ("JVC", "JVC"),
    ("Kenwood", "Kenwood"),
    ("LG", "LG"),
    ("Loewe", "Loewe"),
    ("Marantz", "Marantz"),
    ("McIntosh", "McIntosh"),
    ("Mystery", "Mystery"),
    ("NAD", "NAD"),
    ("NOVIS", "NOVIS"),
    ("ODEON", "ODEON"),
    ("Onkyo", "Onkyo"),
    ("Orion", "Orion"),
    ("Panasonic", "Panasonic"),
    ("Philips", "Philips"),
    ("Pioneer", "Pioneer"),
    ("Rolsen", "Rolsen"),
    ("Samsung", "Samsung"),
    ("Sharp", "Sharp"),
    ("Sherwood", "Sherwood"),
    ("Sony", "Sony"),
    ("Soundmax", "Soundmax"),
    ("Supra", "Supra"),
    ("SVEN", "SVEN"),
    ("TELEFUNKEN", "TELEFUNKEN"),
    ("Toshiba", "Toshiba"),
    ("Vitek", "Vitek"),
    ("VR", "VR"),
    ("Xoro", "Xoro"),
    ("Yamaha", "Yamaha"),
    ("Другой", "Другой"),

    # Видеокамеры
    ("Canon", "Canon"),
    ("HP", "HP"),
    ("JVC", "JVC"),
    ("Kodak", "Kodak"),
    ("Nobelic", "Nobelic"),
    ("Oregon", "Oregon"),
    ("Panasonic", "Panasonic"),
    ("Praktica", "Praktica"),
    ("Samsung", "Samsung"),
    ("Sanyo", "Sanyo"),
    ("Sony", "Sony"),
    ("Toshiba", "Toshiba"),
    ("Другой", "Другой"),

    # Проекторы
    ("3M", "3M"),
    ("Acer", "Acer"),
    ("ASUS", "ASUS"),
    ("BenQ", "BenQ"),
    ("Canon", "Canon"),
    ("Dell", "Dell"),
    ("EIKI", "EIKI"),
    ("Epson", "Epson"),
    ("Hitachi", "Hitachi"),
    ("iconBIT", "iconBIT"),
    ("InFocus", "InFocus"),
    ("JVC", "JVC"),
    ("Merlin", "Merlin"),
    ("Mitsubishi Electric", "Mitsubishi Electric"),
    ("NEC", "NEC"),
    ("Oldi", "Oldi"),
    ("Optoma", "Optoma"),
    ("Panasonic", "Panasonic"),
    ("Philips", "Philips"),
    ("Promate", "Promate"),
    ("Ricoh", "Ricoh"),
    ("Samsung", "Samsung"),
    ("Sanyo", "Sanyo"),
    ("Sony", "Sony"),
    ("Toshiba", "Toshiba"),
    ("ViewSonic", "ViewSonic"),
    ("Vivitek", "Vivitek"),
    ("Другой", "Другой"),

    # спутниковые ресиверы
    ("AB-COM", "AB-COM"),
    ("Arion", "Arion"),
    ("AzBox", "AzBox"),
    ("DGStation", "DGStation"),
    ("Dr.HD", "Dr.HD"),
    ("Dreambox", "Dreambox"),
    ("Dreamsky", "Dreamsky"),
    ("Galaxy Innovations", "Galaxy Innovations"),
    ("General Satellite", "General Satellite"),
    ("Golden Media", "Golden Media"),
    ("Humax", "Humax"),
    ("Kathrein", "Kathrein"),
    ("Openbox", "Openbox"),
    ("Opentech", "Opentech"),
    ("Opticum", "Opticum"),
    ("Rolsen", "Rolsen"),
    ("Sagemcom", "Sagemcom"),
    ("Samsung", "Samsung"),
    ("Sezam", "Sezam"),
    ("Skyon", "Skyon"),
    ("SKYTER", "SKYTER"),
    ("Skyway", "Skyway"),
    ("Thomson", "Thomson"),
    ("Topfield", "Topfield"),
    ("WayteQ", "WayteQ"),
    ("World Vision", "World Vision"),
    ("Другой", "Другой"),

    # ТВ-тюнеры
    ("ADS Tech", "ADS Tech"),
    ("ASUS", "ASUS"),
    ("AverMedia", "AverMedia"),
    ("Beholder", "Beholder"),
    ("Compro", "Compro"),
    ("Digitus", "Digitus"),
    ("EasyCap", "EasyCap"),
    ("Gigabyte", "Gigabyte"),
    ("iconBIT", "iconBIT"),
    ("Intex", "Intex"),
    ("KWorld", "KWorld"),
    ("Leadtek", "Leadtek"),
    ("PCTV", "PCTV"),
    ("Prolink", "Prolink"),
    ("Другой", "Другой"),
]   # производитель ТВ и видеотехники

###### БАНКЕТКИ ######
OTTOMANS_TYPE = [
    ('Банкетки', 'Банкетки'),
    ('Пуфики', 'Пуфики'),
    ('Прочее', 'Прочее'),
]   # тип

###### ВЕШАЛКИ, ПРИХОЖИЕ ######
HANGER_TYPE = [
    ('Вешалки', 'Вешалки'),
    ('Наборы для прихожей', 'Наборы для прихожей'),
    ('Прочее', 'Прочее'),
]   # тип
HANGER_FASTENING = [
    ('Настенный', 'Настенный'),
    ('Напольный', 'Напольный'),
    ('Потолочный', 'Потолочный'),
]   # способ крепления