# Generated by Django 5.0 on 2024-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='car',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='phone3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.AddField(
            model_name='car',
            name='phone_1',
            field=models.CharField(default='', max_length=9, verbose_name='Номер телефона 1'),
        ),
        migrations.AddField(
            model_name='car',
            name='phone_2',
            field=models.CharField(default='', max_length=9, verbose_name='Номер телефона 2'),
        ),
        migrations.AddField(
            model_name='car',
            name='phone_3',
            field=models.CharField(default='', max_length=9, verbose_name='Номер телефона 3'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='Car', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='Car', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='Car', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='Car', verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='Car', verbose_name='Фото 5'),
        ),
    ]
