# Generated by Django 5.0 on 2024-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_car_accounting_alter_car_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='phone_2',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Номер телефона 2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='phone_3',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Номер телефона 3'),
        ),
    ]
