# Generated by Django 5.0 on 2024-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_car_asr_remove_car_region_alter_car_phone_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='accounting',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Учёт'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя продавца'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна регистрации'),
        ),
    ]
