# Generated by Django 5.0 on 2024-02-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_car_phone_2_alter_car_phone_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='asr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='region',
        ),
        migrations.AlterField(
            model_name='car',
            name='phone_1',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Номер телефона 1'),
        ),
    ]
